### ISSUE TITLE
Docker compose, Adding multiply bots

### ISSUE THREAD

**Issue by Immortality-IMT** [freqtrade/frequi#1930]
* FreqUI Version: 1.3.1
  * Operating system: Linux Mint 21.3
  * Python Version: Python 3.10.12
  * CCXT version: ccxt==4.3.42
  * Freqtrade Version: freqtrade 2024.5
  
How to add multiple bots in docker, docker-compose with frequi.

I have tried every combination of configuration.

Here is my configs...
Main:

```dockerfile

    "api_server": {
        "enabled": true,
        "listen_ip_address": "0.0.0.0",
        "listen_port": 8080,
         "CORS_origins": [],
         .....
    }
```
Next Bot
```
    "api_server": {
        "enabled": true,
        "listen_ip_address": "0.0.0.0",
        "listen_port": 8081,
         "CORS_origins": ["http://127.0.0.1:8080"],
         .....
    }
```
Docker compose:
```
version: '3'
services:
  freqtrade1:
    image: my-freqtrade
    restart: always
    container_name: freqtrade1
    volumes:
      - "~/.freqtrade/user_data/SampleStrategy1:/freqtrade/user_data"
      - "~/.freqtrade/user_data/SampleStrategy1/config.json:/freqtrade/config.json"
      - "~/.freqtrade/user_data/SampleStrategy1/tradesv3.sqlite:/freqtrade/tradesv3.sqlite"
    ports:
      - "127.0.0.1:8080:8080"
    command: >
      trade
      --logfile /freqtrade/user_data/freqtrade.log
      --db-url sqlite:///tradesv3.sqlite
      --config /freqtrade/config.json
      --strategy SampleStrategy1

  freqtrade2:
    image: my-freqtrade
    restart: always
    container_name: freqtrade2
    volumes:
      - "~/.freqtrade/user_data/SampleStrategy2:/freqtrade/user_data"
      - "~/.freqtrade/user_data/SampleStrategy2/config.json:/freqtrade/config.json"
      - "~/.freqtrade/user_data/SampleStrategy2/tradesv3.sqlite:/freqtrade/tradesv3.sqlite"
    ports:
      - "127.0.0.1:8081:8080"
    command: >
      trade
      --logfile /freqtrade/user_data/freqtrade.log
      --db-url sqlite:///tradesv3.sqlite
      --config /freqtrade/config.json
      --strategy SampleStrategy2
```
Please test it before replying, as I have tested different IP combinations looking for the API. I still think it's the IP combination, but I am believing the api is not accessible. I am able to add the main bot, not multiple bots. 

The final test is adding the bot via frequi.

Any help appreciated.

**Comment by stash86** [comment]
Can you access the second bot directly?

**Comment by Immortality-IMT** [comment]
No

**Comment by stash86** [comment]
On the config for the second bot, change the listen port to 8080

**Comment by Immortality-IMT** [comment]
It adds the first bot twice, if 8080 bot has 
if config1.json and config2.json also has

        "listen_ip_address": "0.0.0.0",
        "listen_port": 8080,

then it adds the first bot twice.

**Comment by xmatthias** [comment]
It's a simple configuration mistake.

---

if you consider the docker-compose port mapping - it's <IP>:<hostport>:<containerport>.
in your case - it's 127.0.0.1:8081:8080 - which means it's exposed on 8081 - but expects something running internally at 8080.

your (2nd) config however uses 8081 as port - which is therefore a disconnect.

For Docker deployments - i usually recommend using the identical port internally (8080) - and use portmappings to have different ports exposed - which in your case - would mean you change listen_port to 8080 - and it'll work.

Your cors configuration is correct - IF you're accessing your UI via http://127.0.0.1:8080. If you use http://localhost:8080 in your browser (or ANY other URL), it'll no longer work (CORS is VERY picky in this regard).

**Comment by Immortality-IMT** [comment]
The first bot logs in, then using http://127.0.0.1:8081 on frequi log into your bot returns the Login failed... You can verify this by navigating to http://127.0.0.1:8081/api/v1/ping which returns The connection was reset browser error.

The config is...

Main bot:
```
    "api_server": {
        "enabled": true,
        "listen_ip_address": "0.0.0.0",
        "listen_port": 8080,
        "CORS_origins": []
       .....
```
and second bot
```    "api_server": {
        "enabled": true,
        "listen_ip_address": "0.0.0.0",
        "listen_port": 8081,
        "CORS_origins": ["http://127.0.0.1:8080"]
       .....
````

docker-compose for the two bots are...

```
version: '3'
services:
  freqtrade1:
    image: my-freqtrade
    restart: always
    container_name: freqtrade1
    volumes:
      - "~/.freqtrade/user_data/SampleStrategy1:/freqtrade/user_data"
      - "~/.freqtrade/user_data/SampleStrategy1/config.json:/freqtrade/config.json"
      - "~/.freqtrade/user_data/SampleStrategy1/tradesv3.sqlite:/freqtrade/tradesv3.sqlite"
    ports:
      - "127.0.0.1:8080:8080"
    command: >
      trade
      --logfile /freqtrade/user_data/freqtrade.log
      --db-url sqlite:///tradesv3.sqlite
      --config /freqtrade/config.json
      --strategy SampleStrategy1

  freqtrade2:
    image: my-freqtrade
    restart: always
    container_name: freqtrade2
    volumes:
      - "~/.freqtrade/user_data/SampleStrategy2:/freqtrade/user_data"
      - "~/.freqtrade/user_data/SampleStrategy2/config.json:/freqtrade/config.json"
      - "~/.freqtrade/user_data/SampleStrategy2/tradesv3.sqlite:/freqtrade/tradesv3.sqlite"
    ports:
      - "127.0.0.1:8081:8080"
    command: >
      trade
      --logfile /freqtrade/user_data/freqtrade.log
      --db-url sqlite:///tradesv3.sqlite
      --config /freqtrade/config.json
      --strategy SampleStrategy2
```
When log in to frequi I put http://127.0.0.1:8081 for the second bot.
